# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
---
repos:
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 96ee1570b119e6337aafcc2f299bb0d902b68328  # frozen: 0.28.6
    hooks:
      - id: check-github-workflows
  - repo: https://github.com/SonarSource/sonar-secrets-pre-commit
    rev: v2.32.0.9670
    hooks:
      - id: sonar-secrets
        stages: [ pre-commit ]