language: java
sudo: false
install: true

jdk:
  - oraclejdk7

env:
  - JOB=H2
  - JOB=POSTGRES
  - JOB=MYSQL
  - JOB=WEB
  - JOB=ITS IT_CATEGORY=issue
  - JOB=ITS IT_CATEGORY=measure
  - JOB=ITS IT_CATEGORY=plugins
  - JOB=ITS IT_CATEGORY=qualitygate
  - JOB=ITS IT_CATEGORY=testing
  - JOB=ITS IT_CATEGORY=ui
  - JOB=ITS IT_CATEGORY=updatecenter

matrix:
  fast_finish: true

script:
  - ./travis.sh

cache:
  directories:
    - '$HOME/.m2/repository'
    - 'server/sonar-web/node'
    - 'server/sonar-web/node_modules'

before_cache:
  - 'rm -rf $HOME/.m2/repository/org/codehaus/sonar'
  - 'rm -f server/sonar-web/npm-debug.log'

notifications:
  email: false
