language: java
sudo: required
install: true
jdk: oraclejdk8
script: ./travis.sh
dist: trusty

env:
  - TARGET=BUILD

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar
    - server/sonar-web/node
    - server/sonar-web/node_modules
    - $HOME/jvm
    - $HOME/maven
    - $HOME/phantomjs

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of mvn deploy
  - rm -rf $HOME/.m2/repository/org/sonarsource/sonarqube
  - find $HOME/.m2 -name resolver-status.properties -exec rm {} \;

notifications:
  email: false
  webhooks:
    - secure: "fdrl+bghdHZF9snbp0vNlKY6JBn7Y9GZAfE3EtUTtgeio6LBIA5es1pBrSHckMbuxjjDJbzDZ+DtNkkQxJ0uR4rirUGgktayDfP/pjjFRYstJiOzMxpFJ0Cmkbn2KAA2LKEWOlWUGoFUFBOYq/p2mh9XYw1pACtdb+lIB653Zc4="
  on_start: never
  on_success: always
  on_failure: always
  on_cancel: never
  on_error: always
