base: &base
  adapter: jdbc
  dialect: <%= ::Java::OrgSonarServerUi::JRubyFacade.getInstance().getDatabase().getDialect().getActiveRecordDialectCode() %>
  pool: <%= ::Java::OrgSonarServerUi::JRubyFacade.getInstance().getConfigurationValue('sonar.jdbc.maxActive') || 60 %>

development:
  <<: *base

production:
  <<: *base

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
